### ISSUE TITLE
Try to use compileall2 in Fedora

### ISSUE THREAD

**Issue by hroncok** [fedora-python/compileall2#3]
I'll try to hack on python-rpm-macros and brp-python-bytecompile to use compileall2.

Let's see how far I get.

**Comment by hroncok** [comment]
python-rpm-macros https://github.com/hroncok/python-rpm-macros/pull/1

**Comment by frenzymadness** [comment]
I've created two PRs with fixes and then I'll release a new version. Then, we can test this.

**Comment by frenzymadness** [comment]
New version 0.4.0 released.

**Comment by hroncok** [comment]
Thanks. I won't have time to look into this until the end of month.

**Comment by frenzymadness** [comment]
Built of RPM macros proposed in https://github.com/hroncok/python-rpm-macros/pull/1 is ready in COPR https://copr.fedorainfracloud.org/coprs/lbalhar/compileall2/builds/

I did a release update before the build.

Next step is to switch brp-python-bytecompile to compileall2.

**Comment by hroncok** [comment]
see https://github.com/hroncok/redhat-rpm-config/pull/1

also, in copr, make sure that both adapted packages' (epoch-)version-release is higher than in actual Fedora (possibly by introducing epoch or artifitially bumping the version by a large number).
