### ISSUE TITLE
RFE: Add CLI argument for pyc invalidation mode

### ISSUE THREAD

**Issue by hroncok** [fedora-python/compileall2#9]
It would be nice if compileall2 supported a CLI argument for setting the desired [pyc invalidation mode](https://www.python.org/dev/peps/pep-0552/).

**Comment by frenzymadness** [comment]
It's there but it works only for Python 3.7 and higher. https://github.com/fedora-python/compileall2/blob/master/compileall2.py#L382

**Comment by hroncok** [comment]
Good. That should be enough. Sorry for not checking the code.
